server:
  port: 8080
  ssl:
    key-store: /usr/springboot1wayssl/client/certs/abcdkeystore.jks
    key-store-password: 123456
    trust-store: /usr/springboot1wayssl/client/certs/abcdtruststore.jks
    trust-store-password: 123456
    key-store-type: jks
    trust-store-type: jks
