server:
  port: 8443
  ssl:
    key-store: classpath:globekeystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    trust-store: classpath:globetruststore.p12
    trust-store-password: 123456
    trust-store-type: PKCS12
    client-auth: need
